---
name: Build and Optionally Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.release.outputs.published }}
      release-git-tag: ${{ steps.release.outputs.release-git-tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Setup buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Only
      uses: docker/bake-action@v5
      with:
        files: |
          ./docker-bake.hcl

    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push
      if: steps['release']['outputs']['published'] == 'true'
      uses: docker/bake-action@v5
      env:
        TAG: ${{steps.release.outputs.release-version}}
      with:
        push: 'true'

  done:
    needs: [release]
    name: Done
    if: needs.release.result == 'success'
    runs-on: ubuntu-latest
    steps:
    - run: echo 'done'

  cleanup:
    needs: [release]
    if: failure()
    name: Cleanup Half-Created Release/Tag
    runs-on: ubuntu-latest
    steps:
    - name: Delete GitHub Release
      run: |
        if gh release view ${{ needs.release.outputs.release-git-tag }} >/dev/null 2>&1; then
          gh release delete ${{ needs.release.outputs.release-git-tag }} --yes
        fi
    - name: Delete GitHub Tag
      run: |
        if git show-ref --tags ${{ needs.release.outputs.release-git-tag }}; then
          git tag -d ${{ needs.release.outputs.release-git-tag }}
          git push origin :refs/tags/${{ needs.release.outputs.release-git-tag }}
        fi
